/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Acceso;

import java.sql.*;
import javax.swing.*;
import com.sun.awt.AWTUtilities;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

/**
 *
 * @author Misael
 */
public class FrmAccesorio extends javax.swing.JFrame {

    int x, y;
    static Connection conn = null;
    static Statement st = null;
    static ResultSet rs = null;
    static ResultSet rs1 = null;
    static ResultSet rs2 = null;

    /**
     * Creates new form FrmAccesorio
     */
    public FrmAccesorio() {
        initComponents();
        setLocationRelativeTo(null);
        btnguardar.setEnabled(false);
        btnmodificar.setEnabled(false);
        btncancelar.setVisible(false);

        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 27, 27);
        AWTUtilities.setWindowShape(this, forma);
        buttontransparente();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/logo.png")));

    }

    public void buttontransparente() {
        btncerrar.setOpaque(false);
        btncerrar.setContentAreaFilled(false);
        btncerrar.setBorderPainted(false);
    }

    public void cargarcodigo()//ESTE ES UN GENERADOR DE CODIGOS AUTOMATICOS PROFE, ESTUVE INVESTIGANDO PARA QUE NO ESTE PONIENDO A CADA RATO ESPERO LE GUSTE
    {

        int j;
        String num = "";
        String c = "";
        String SQL = "select max(id_accesorios_dispositivo) from nueva_acce";
        try {
            conn = GenerarCodigo.Enlace(conn);
            st = conn.createStatement();
            rs = st.executeQuery(SQL);
            if (rs.next()) {
                c = rs.getString(1);
            }

            if (c == null) {
                txtidaccesorios.setText("000001");
            } else {
                char r1 = c.charAt(2);
                char r2 = c.charAt(3);
                char r3 = c.charAt(4);
                char r4 = c.charAt(5);
                String r = "";
                r = "" + r1 + r2 + r3 + r4;

                j = Integer.parseInt(r);
                GenerarCodigo gen = new GenerarCodigo();
                gen.generar(j);
                txtidaccesorios.setText("00" + gen.serie());

            }

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        paccesorios = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtdesacce = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbored = new javax.swing.JComboBox();
        cbobateria = new javax.swing.JComboBox();
        cbobluetooth = new javax.swing.JComboBox();
        cbowebcam = new javax.swing.JComboBox();
        cbocargador = new javax.swing.JComboBox();
        cboco = new javax.swing.JComboBox();
        cboa = new javax.swing.JComboBox();
        btncancelar = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btncerrar = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtidaccesorios = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnnuevoregi = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paccesorios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 10));
        paccesorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Cargador:");
        paccesorios.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Bateria:");
        paccesorios.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Web Cam:");
        paccesorios.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Bluetooth");
        paccesorios.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Accesorios:");
        paccesorios.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Descripcion:");
        paccesorios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));
        paccesorios.add(txtdesacce, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 110, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Red:");
        paccesorios.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Color:");
        paccesorios.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        cbored.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CABLE", "WIFI", "AMBOS" }));
        paccesorios.add(cbored, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 90, -1));

        cbobateria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));
        paccesorios.add(cbobateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 60, -1));

        cbobluetooth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));
        paccesorios.add(cbobluetooth, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        cbowebcam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));
        paccesorios.add(cbowebcam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        cbocargador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));
        paccesorios.add(cbocargador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        cboco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIN COLOR", "ROJO", "AZUL", "AMARILLO", "NEGRO", "OTRO" }));
        cboco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocoActionPerformed(evt);
            }
        });
        paccesorios.add(cboco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 90, -1));

        cboa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIN ACCESORIO", "MALETINES", "BOLSO", "MOCHILA", "OTRO" }));
        paccesorios.add(cboa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, -1));

        btncancelar.setBackground(new java.awt.Color(0, 204, 255));
        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/CANCELAR.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setToolTipText("");
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        paccesorios.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 140, 30));

        getContentPane().add(paccesorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1160, 130));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setText("ACCESORIOS");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 10));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar.png"))); // NOI18N
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 50, 30));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo_agua.png"))); // NOI18N
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 510));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("CNT + C");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("ACCESORIOS");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel1.add(txtidaccesorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("COPIAR CODIGO -->");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnguardar.setBackground(new java.awt.Color(0, 204, 255));
        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/guardar_pequeño.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setToolTipText("");
        btnguardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 120, 30));

        btnnuevoregi.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        btnnuevoregi.setForeground(new java.awt.Color(0, 0, 153));
        btnnuevoregi.setText("Nuevo Registro");
        btnnuevoregi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoregiActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevoregi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        btnbuscar.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(0, 0, 153));
        btnbuscar.setText("Buscar Registro");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, -1, -1));

        btnmodificar.setBackground(new java.awt.Color(0, 204, 255));
        btnmodificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificar_pequeño.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setToolTipText("");
        btnmodificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        btnnuevoregi.setEnabled(true);
        //  noeditable(false,false,false,false,false,false);
        int resp;

        resp = JOptionPane.showConfirmDialog(null, "¿Desea grabar el registro?", "Pregunta", 0);
        if (resp == 0) {
            try {
                conn = Acceso.Enlace(conn);
                st = Acceso.sta(st);
                rs = Acceso.EnlAccesorios(rs);
                //variables
                String comando, cod, cargador, webcam, bateria, bluetooth, red, idac, maracces, descripcion, idco, marcol;
                //variables
                cod = txtidaccesorios.getText();
                cargador = (String) cbocargador.getSelectedItem();
                webcam = (String) cbowebcam.getSelectedItem();
                bateria = (String) cbobateria.getSelectedItem();
                bluetooth = (String) cbobluetooth.getSelectedItem();
                red = (String) cbored.getSelectedItem();
                maracces = (String) cboa.getSelectedItem();

                descripcion = txtdesacce.getText();
                marcol = (String) cboco.getSelectedItem();

                //COMANDOS
                comando = "INSERT INTO nueva_acce VALUES('" + cod + "','" + cargador + "','" + webcam + "','" + bateria + "',"
                        + "'" + bluetooth + "','" + red + "','" + maracces + "','" + descripcion + "','" + marcol + "')";
                st.executeUpdate(comando);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Demasiados Caracteres, resume mejor");
                JOptionPane.showMessageDialog(null, "Error " + e.toString());
                return;
                //
            }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnnuevoregiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoregiActionPerformed
        cargarcodigo();
        //txtcarapro.setText("");
        //txtmodelolaptop.setText("");
        btncancelar.setVisible(true);
        btnguardar.setEnabled(true);
        // editable(true,true,true,true,true,true,true,true,true,true,true,true);
        btnnuevoregi.setEnabled(false);
    }//GEN-LAST:event_btnnuevoregiActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        String BuscarLaptop;//BUSCAMOS LOS CLIENTES EN LA BASE DE DATOS SEGUN SUS CODIGOS
        //editable(true,true,true,true,true,true,true,true,true,true,true,true);
        btnmodificar.setEnabled(true);
        if (btnnuevoregi.isEnabled()) {
            try {
                conn = Acceso.Enlace(conn);
                rs = Acceso.EnlAccesorios(rs);
                BuscarLaptop = txtidaccesorios.getText();
                boolean encuentra = false;
                while (rs.next()) {
                    if (BuscarLaptop.equals(rs.getString(1))) {

                        cbocargador.setSelectedItem((String) rs.getString(2));
                        cbowebcam.setSelectedItem((String) rs.getString(3));
                        cbobateria.setSelectedItem((String) rs.getString(4));
                        cbobluetooth.setSelectedItem((String) rs.getString(5));
                        cbored.setSelectedItem((String) rs.getString(6));
                        cboa.setSelectedItem((String) rs.getString(7));
                        txtdesacce.setText((String) rs.getString(8));
                        cboco.setSelectedItem((String) rs.getString(9));

                        encuentra = true;
                        break;
                    }
                }
                if (encuentra == false)//SI NO SE ENCUENTRA EL CODIGO DEBERAN SALDRA EL MENSAJE DE NO EXISTEN DATOS
                {
                    JOptionPane.showMessageDialog(null, "No se hallan datos, corrija el codigo");
                    txtidaccesorios.setText("NO EXISTE");

                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR BD" + e.getMessage());
            }
        }

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        int resp;
        //noeditable(false,false,false,false,false,false,false,false,false,false,false,true);
        resp = JOptionPane.showConfirmDialog(null, "¿Desea modificar el registro?", "Pregunta", 0);
        if (resp == 0) {
            try {
                conn = Acceso.Enlace(conn);
                st = Acceso.sta(st);
                rs = Acceso.EnlAccesorios(rs);
                //variables
                String comando, cod, cargador, webcam, bateria, bluetooth, red, idac, maracces, descripcion, idco, marcol;
                //variables
                cod = txtidaccesorios.getText();
                cargador = (String) cbocargador.getSelectedItem();
                webcam = (String) cbowebcam.getSelectedItem();
                bateria = (String) cbobateria.getSelectedItem();
                bluetooth = (String) cbobluetooth.getSelectedItem();
                red = (String) cbored.getSelectedItem();
                idac = (String) cboa.getSelectedItem();

                descripcion = txtdesacce.getText();
                idco = (String) cboco.getSelectedItem();

                comando = "UPDATE nueva_acce SET cargador='" + cargador + "', web_cam='" + webcam + "',bateria='" + bateria + "'"
                        + ",bluetooth='" + bluetooth + "',red='" + red + "',accesori='" + idac + "',descripcion='" + descripcion + "'"
                        + ",color='" + idco + "'";
                comando = comando + " WHERE id_accesorios_dispositivo=" + cod;
                st.executeUpdate(comando);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "¡Hey eso no puedes hacer!, verifica no cambiar el codigo de la Laptop");
                return;
                // JOptionPane.showMessageDialog(null, "Error "+e.toString());
            }
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void cbocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbocoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        int resp;
        resp = JOptionPane.showConfirmDialog(null, "¿Desea cancelar el proceso?", "Pregunta", 0);
        if (resp == 0) {
            txtidaccesorios.setText("");
            btnbuscar.setEnabled(true);
            btnnuevoregi.setEnabled(true);
            btnguardar.setEnabled(false);

            //noeditable(true,false,false,false,false,false,false,false,false,false,false,false);
            btncancelar.setVisible(false);
        }
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAccesorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAccesorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAccesorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAccesorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAccesorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevoregi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox cboa;
    private javax.swing.JComboBox cbobateria;
    private javax.swing.JComboBox cbobluetooth;
    private javax.swing.JComboBox cbocargador;
    private javax.swing.JComboBox cboco;
    private javax.swing.JComboBox cbored;
    private javax.swing.JComboBox cbowebcam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel paccesorios;
    private javax.swing.JTextField txtdesacce;
    private javax.swing.JTextField txtidaccesorios;
    // End of variables declaration//GEN-END:variables
}
