/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Acceso;

import java.sql.*;
import javax.swing.*;
import com.sun.awt.AWTUtilities;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

/**
 *
 * @author Misael
 */
public class FrmCliente extends javax.swing.JFrame {

    static Connection conn = null;
    static Statement st = null;
    static ResultSet rs = null;
    static ResultSet rs1 = null;
    int x, y;

    /**
     * Creates new form FrmCliente
     */
    public FrmCliente() {
        initComponents();
        buttontransparente();
        btnguardar.setEnabled(false);
        btnmodificar.setEnabled(false);
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 27, 27);
        AWTUtilities.setWindowShape(this, forma);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/logo.png")));

    }

    public void cargarcodigo()//ESTE ES UN GENERADOR DE CODIGOS AUTOMATICOS PROFE, ESTUVE INVESTIGANDO PARA QUE NO ESTE PONIENDO A CADA RATO ESPERO LE GUSTE
    {

        int j;
        String num = "";
        String c = "";
        String SQL = "select max(id_cliente) from cliente";
        try {
            conn = GenerarCodigo.Enlace(conn);
            st = conn.createStatement();
            rs = st.executeQuery(SQL);
            if (rs.next()) {
                c = rs.getString(1);
            }

            if (c == null) {
                lblcodigocli.setText("000001");
            } else {
                char r1 = c.charAt(2);
                char r2 = c.charAt(3);
                char r3 = c.charAt(4);
                char r4 = c.charAt(5);
                String r = "";
                r = "" + r1 + r2 + r3 + r4;

                j = Integer.parseInt(r);
                GenerarCodigo gen = new GenerarCodigo();
                gen.generar(j);
                lblcodigocli.setText("00" + gen.serie());

            }

        } catch (Exception e) {
        }

    }

    public void buttontransparente() {
        btncerrar.setOpaque(false);
        btncerrar.setContentAreaFilled(false);
        btncerrar.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnmodificar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        lblcodigocli = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        txtnombre_cli = new javax.swing.JTextField();
        txtnumerodocu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbotipdoc = new javax.swing.JComboBox();
        btncerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmodificar.setBackground(new java.awt.Color(255, 255, 153));
        btnmodificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificar_pequeño.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setToolTipText("");
        btnmodificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 30));

        btnguardar.setBackground(new java.awt.Color(0, 204, 255));
        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/guardar_pequeño.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setToolTipText("");
        btnguardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 120, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cliente_png.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 120));

        btnbuscar.setBackground(new java.awt.Color(204, 255, 204));
        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bucar_pequeño.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.setToolTipText("");
        btnbuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 120, 30));

        lblcodigocli.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jPanel2.add(lblcodigocli, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel8.setText("Codigo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnnuevo.setBackground(new java.awt.Color(0, 204, 0));
        btnnuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/agregar_pequeño.png"))); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 400));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel3.setText("DATOS DEL CLIENTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel5.setText("Telefono:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel2.setText("Tipo de Documento:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel7.setText("Numero del Documento:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel3.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 180, -1));
        jPanel3.add(txtnombre_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 180, -1));
        jPanel3.add(txtnumerodocu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 180, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel9.setText("Señor(es):");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        cbotipdoc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbotipdoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccionar>", "DNI", "RUT", "CARNET DE EXTRANJE", "OTRO" }));
        jPanel3.add(cbotipdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 180, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 380, 290));

        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar.png"))); // NOI18N
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 50, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo_titulo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        int resp;

        resp = JOptionPane.showConfirmDialog(null, "¿Desea grabar el registro?", "Pregunta", 0);
        if (resp == 0) {
            try {
                conn = Acceso.Enlace(conn);
                st = Acceso.sta(st);
                rs = Acceso.EnlCliente(rs);
                //variables
                String comando, cod, nomcli, tipodoc, numdoc, telcli;
                //variables
                cod = lblcodigocli.getText();
                nomcli = txtnombre_cli.getText();
                tipodoc = String.valueOf(cbotipdoc.getSelectedItem());
                numdoc = txtnumerodocu.getText();
                telcli = txttelefono.getText();

                //COMANDOS
                comando = "INSERT INTO cliente VALUES('" + cod + "','" + nomcli + "','" + tipodoc + "','" + numdoc + "','" + telcli + "')";
                st.executeUpdate(comando);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error " + e.toString());
            }
            btnguardar.setEnabled(false);
            btnmodificar.setEnabled(false);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed

        dispose();

    }//GEN-LAST:event_btncerrarActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        int resp;
        resp = JOptionPane.showConfirmDialog(null, "¿Desea modificar el registro?", "Pregunta", 0);
        if (resp == 0) {
            try {
                conn = Acceso.Enlace(conn);
                st = Acceso.sta(st);
                rs = Acceso.EnlCliente(rs);

                String comando, cod, nomcli, tipodoc, numdoc, telcli;
                //variables
                cod = lblcodigocli.getText();
                nomcli = txtnombre_cli.getText();
                tipodoc = String.valueOf(cbotipdoc.getSelectedItem());
                numdoc = txtnumerodocu.getText();
                telcli = txttelefono.getText();

                comando = "UPDATE cliente SET nombre_cliente='" + nomcli + "',tipo_documento='" + tipodoc + "'"
                        + ",numero_documento='" + numdoc + "',telefono='" + telcli + "' ";
                comando = comando + " WHERE id_cliente=" + cod;
                st.executeUpdate(comando);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error " + e.toString());
            }
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        cargarcodigo();
        btnguardar.setEnabled(true);
        btnmodificar.setEnabled(true);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String b, b1, b2;

        btnmodificar.setEnabled(true);
        if (btnnuevo.isEnabled()) {
            try {
                conn = Acceso.Enlace(conn);
                rs = Acceso.EnlCliente(rs);
      //  b = (String)cbbuscaidcli.getSelectedItem();
                // b1 = txtnomcli.getText();
                b2 = txtnumerodocu.getText();
                boolean encuentra = false;
                while (rs.next()) {
                    if (b2.equals(rs.getString(4))) {
                        lblcodigocli.setText((String) rs.getString(1));
                        txtnombre_cli.setText((String) rs.getString(2));
                        cbotipdoc.setSelectedItem((String) rs.getString(3));
                        txttelefono.setText((String) rs.getString(5));

                        encuentra = true;
                        break;
                    }
                }
                if (encuentra = false) {
                    txtnombre_cli.setText("NO EXISTE");

                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR BD" + e.getMessage());
            }

        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox cbotipdoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblcodigocli;
    private javax.swing.JTextField txtnombre_cli;
    private javax.swing.JTextField txtnumerodocu;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
