/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Acceso;

import java.sql.*;
import javax.swing.*;
import com.sun.awt.AWTUtilities;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;

/**
 *
 * @author Misael
 */
public class FrmImpresora extends javax.swing.JFrame {

    static Connection conn = null;
    static Statement st = null;
    static ResultSet rs = null;
    static ResultSet rs10 = null;
    int x, y;

    DefaultComboBoxModel marcaimpresora = new DefaultComboBoxModel();

    /**
     * Creates new form FrmImpresora
     */
    public FrmImpresora() {
        initComponents();
        buttontransparente();
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 27, 27);
        AWTUtilities.setWindowShape(this, forma);
        buttontransparente();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Recursos/logo.png")));
        pimpresora.setEnabled(false);
        noeditable(false, false, false, false, false, false);
        cbomarcaimpresora.setModel(marcaimpresora);
        btncancelar.setVisible(false);
        try {
            conn = Acceso.Enlace(conn);
            rs10 = Acceso.obtenerMarcaImpresora(rs10);

            while (rs10.next()) {
                marcaimpresora.addElement(rs10.getString(1));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error BD" + e.getMessage());
        }
    }

    public void cargarcodigo()//ESTE ES UN GENERADOR DE CODIGOS AUTOMATICOS PROFE, ESTUVE INVESTIGANDO PARA QUE NO ESTE PONIENDO A CADA RATO ESPERO LE GUSTE
    {

        int j;
        String num = "";
        String c = "";
        String SQL = "select max(id_impresora) from impresora";
        try {
            conn = GenerarCodigo.Enlace(conn);
            st = conn.createStatement();
            rs = st.executeQuery(SQL);
            if (rs.next()) {
                c = rs.getString(1);
            }

            if (c == null) {
                txtidimpresora.setText("000001");
            } else {
                char r1 = c.charAt(2);
                char r2 = c.charAt(3);
                char r3 = c.charAt(4);
                char r4 = c.charAt(5);
                String r = "";
                r = "" + r1 + r2 + r3 + r4;

                j = Integer.parseInt(r);
                GenerarCodigo gen = new GenerarCodigo();
                gen.generar(j);
                txtidimpresora.setText("00" + gen.serie());

            }

        } catch (Exception e) {
        }

    }

    public void noeditable(boolean c, boolean i, boolean d, boolean l, boolean nu, boolean ae) {
        cbomarcaimpresora.setEnabled(false);
        cbotipoimpresion.setEnabled(false);
        txtdescrip.setEnabled(false);
        txtmodelos.setEnabled(false);
        txtfallos.setEnabled(false);
        btnguardar.setEnabled(false);

    }

    public void editable(boolean c, boolean i, boolean d, boolean l, boolean nu, boolean ae) {
        cbomarcaimpresora.setEnabled(true);
        cbotipoimpresion.setEnabled(true);
        txtdescrip.setEnabled(true);
        txtmodelos.setEnabled(true);
        txtfallos.setEnabled(true);
        btnguardar.setEnabled(true);

    }

    public void buttontransparente() {
        btncerrar.setOpaque(false);
        btncerrar.setContentAreaFilled(false);
        btncerrar.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pimpresora = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbotipoimpresion = new javax.swing.JComboBox();
        cbomarcaimpresora = new javax.swing.JComboBox();
        txtdescrip = new javax.swing.JTextField();
        txtmodelos = new javax.swing.JTextField();
        txtfallos = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtidimpresora = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        btncerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnnuevoregi = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pimpresora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        pimpresora.setForeground(new java.awt.Color(0, 0, 102));
        pimpresora.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Marca:");
        pimpresora.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Descripción:");
        pimpresora.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Modelo:");
        pimpresora.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Tipo de Impresión:");
        pimpresora.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Fallos:");
        pimpresora.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        cbotipoimpresion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SISTEMA CONTINUO", "TONER", "CARTUCHO", "OTRO" }));
        pimpresora.add(cbotipoimpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 150, -1));

        pimpresora.add(cbomarcaimpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 110, -1));
        pimpresora.add(txtdescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 350, -1));
        pimpresora.add(txtmodelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 110, -1));
        pimpresora.add(txtfallos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 260, -1));

        btncancelar.setBackground(new java.awt.Color(0, 204, 255));
        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/CANCELAR.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setToolTipText("");
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        pimpresora.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 140, 30));

        getContentPane().add(pimpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1020, 150));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setText("DATOS DEL DISPOSITIVO - \"IMPRESORA\"");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/logo_agua.png"))); // NOI18N
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 510));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 10));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DATOS DE LA IMPRESORA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("COPIAR CODIGO -->");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(txtidimpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setText("CNT + C");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar.png"))); // NOI18N
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 50, 30));

        jButton1.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Buscar Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, -1, -1));

        btnnuevoregi.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        btnnuevoregi.setForeground(new java.awt.Color(0, 0, 153));
        btnnuevoregi.setText("Nuevo Registro");
        btnnuevoregi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoregiActionPerformed(evt);
            }
        });
        jPanel1.add(btnnuevoregi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        btnguardar.setBackground(new java.awt.Color(0, 204, 255));
        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/guardar_pequeño.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setToolTipText("");
        btnguardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 120, 30));

        btnmodificar.setBackground(new java.awt.Color(0, 204, 255));
        btnmodificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificar_pequeño.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setToolTipText("");
        btnmodificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnnuevoregiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoregiActionPerformed
        cargarcodigo();
        pimpresora.setEnabled(true);
        editable(true, true, true, true, true, true);
        btnnuevoregi.setEnabled(false);
        btncancelar.setVisible(true);
    }//GEN-LAST:event_btnnuevoregiActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        btnnuevoregi.setEnabled(true);
        noeditable(false, false, false, false, false, false);
        int resp;

        resp = JOptionPane.showConfirmDialog(null, "¿Desea grabar el registro?", "Pregunta", 0);
        if (resp == 0) {
            try {
                conn = Acceso.Enlace(conn);
                st = Acceso.sta(st);
                rs = Acceso.EnlImpresora(rs);
                //variables
                String comando, cod, marimp = "", idmarimp, tipimpre, descripcion, modelo, fallos;
                //variables
                cod = txtidimpresora.getText();
                idmarimp = (String) cbomarcaimpresora.getSelectedItem();
                rs10 = Acceso.obtenerCodMarcImp(rs10, idmarimp);
                if (rs10.next()) {
                    marimp = rs10.getString(1);
                }
                tipimpre = (String) cbotipoimpresion.getSelectedItem();
                descripcion = txtdescrip.getText();
                modelo = txtmodelos.getText();
                fallos = txtfallos.getText();

                //COMANDOS
                comando = "INSERT INTO impresora VALUES('" + cod + "','" + marimp + "','" + tipimpre + "','" + descripcion + "',"
                        + "'" + modelo + "','" + fallos + "')";
                st.executeUpdate(comando);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Demasiados Caracteres, resume mejor");
                return;
                // JOptionPane.showMessageDialog(null, "Error "+e.toString());
            }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        int resp;
        noeditable(false, false, false, false, false, false);
        resp = JOptionPane.showConfirmDialog(null, "¿Desea modificar el registro?", "Pregunta", 0);
        if (resp == 0) {
            try {
                conn = Acceso.Enlace(conn);
                st = Acceso.sta(st);
                rs = Acceso.EnlImpresora(rs);

                String comando, cod, marimp = "", idmarimp, tipimpre, descripcion, modelo, fallos;
                //variables
                cod = txtidimpresora.getText();
                idmarimp = (String) cbomarcaimpresora.getSelectedItem();
                rs10 = Acceso.obtenerCodMarcImp(rs10, idmarimp);
                if (rs10.next()) {
                    marimp = rs10.getString(1);
                }
                tipimpre = (String) cbotipoimpresion.getSelectedItem();
                descripcion = txtdescrip.getText();
                modelo = txtmodelos.getText();
                fallos = txtfallos.getText();

                comando = "UPDATE impresora SET id_marca_impresora='" + marimp + "', tipo_impresion='" + tipimpre + "',descripcion='" + descripcion + "'"
                        + ",modelo='" + modelo + "',fallos='" + fallos + "'";
                comando = comando + " WHERE id_impresora=" + cod;
                st.executeUpdate(comando);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "¡Hey eso no puedes hacer!, verifica no cambiar el codigo de la Impresora");
                return;
            }
        }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String Buscarcliente;//BUSCAMOS LOS CLIENTES EN LA BASE DE DATOS SEGUN SUS CODIGOS
        if (btnnuevoregi.isEnabled()) {
            try {
                conn = Acceso.Enlace(conn);
                rs = Acceso.ObtenerVistaImpresora(rs);
                Buscarcliente = txtidimpresora.getText();
                boolean encuentra = false;
                while (rs.next()) {
                    if (Buscarcliente.equals(rs.getString(1))) {
                        cbomarcaimpresora.setSelectedItem((String) rs.getString(2));
                        cbotipoimpresion.setSelectedItem((String) rs.getString(3));
                        txtdescrip.setText((String) rs.getString(4));
                        txtmodelos.setText((String) rs.getString(5));
                        txtfallos.setText((String) rs.getString(6));
                        editable(true, true, true, true, true, true);
                        encuentra = true;
                        break;
                    }
                }
                if (encuentra == false)//SI NO SE ENCUENTRA EL CODIGO DEBERAN SALDRA EL MENSAJE DE NO EXISTEN DATOS
                {
                    JOptionPane.showMessageDialog(null, "No se hallan datos, corrija el codigo");
                    txtidimpresora.setText("No Existe");

                    editable(true, true, true, true, true, true);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR BD" + e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        int resp;
        resp = JOptionPane.showConfirmDialog(null, "¿Desea cancelar el proceso?", "Pregunta", 0);
        if (resp == 0) {
            txtidimpresora.setText("");

            btnnuevoregi.setEnabled(true);
            btnguardar.setEnabled(false);

            //noeditable(true,false,false,false,false,false,false,false,false,false,false,false);
            btncancelar.setVisible(false);
        }
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmImpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmImpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmImpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmImpresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmImpresora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevoregi;
    private javax.swing.JComboBox cbomarcaimpresora;
    private javax.swing.JComboBox cbotipoimpresion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pimpresora;
    private javax.swing.JTextField txtdescrip;
    private javax.swing.JTextField txtfallos;
    private javax.swing.JTextField txtidimpresora;
    private javax.swing.JTextField txtmodelos;
    // End of variables declaration//GEN-END:variables
}
